name: caviar tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build project
        shell: bash
        run: mkdir bin && cmake -DBUILD_TEST=OFF . && cmake --build . --target caviar -j 12
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install google test
        shell: bash
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make
      - name: build diff tests
        shell: bash
        run: mkdir bin && cmake . && cmake --build . --target diff_tests -j 12
      - name: execute diff tests
        shell: bash
        run: cd bin && ./diff_tests
      - name: check no change
        shell: bash
        run: git diff-files -p --exit-code --diff-filter=ADMR -w
